name: pack

on: [release]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-18.04, windows-2016, macos-10.15]

    runs-on: ${{ matrix.os }}
 
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version : ${{ matrix.python-version }}
 
    - name: Install dependencies and build wheel
      run: |
        python -m pip install --upgrade pip setuptools build
        python -m build

    - uses: actions/upload-artifact@v2
      with:
        name: sample_wheels
        path: dist
        
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
